# -*- encoding : utf-8 -*-
defaults: &defaults
  image_types: ['image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/x-png', 'image/pjpeg']
  encodes: ["UTF-8", "GBK"]
  web_site_name: "中储粮服务网"
  web_site_domain: "http://fwgs.sinograin.com.cn"
  web_site_founded_year: 2011 
  web_site_key_words: "中储粮 服务网 集中采购 电子化平台 中国储备粮管理总公司 粮机"
  company_name: "中国储备粮管理总公司"
  company_short_name: "中储粮总公司"
  # 客户服务电话
  cs_tel: "业务咨询:(010)88016801/88016802/88016607，技术支持:88016617/88016623。"

  # 颜色样式
  colors: [["red", "红色"],["blue", "浅蓝"],["orange", "橙色"],["purple", "紫色"],["green", "绿色"],["muted", "灰色"],["fb", "蓝紫"],["dark", "黑色"],["pink", "粉色"],["grass-green", "草绿"],["sea-blue", "海蓝"],["banana", "黄色"],["dark-orange", "深橙"],["brown", "棕色"]]
  # 文章置顶类型
  top_type: [["不置顶",0], ["普通置顶",1], ["标红置顶",2]]
  # 信息公开类别
  access_permission: [["完全公开",0], ["普通用户",1], ["单位管理员",2]]
  # 状态约定，对6求模，0待定(等待审核)，1有效(纳入统计)，2无效（已作废、已撤销）,3重要（审核不通过），4警告提醒（未提交、 未完成、等待评论、等待发货、等待确认），5其他
  # 对应的颜色分别是 红, 绿, 灰, 浅蓝, 黄, 深蓝
  status_color: ['danger','success','default','info','warning','primary']
  # '已删除'统一定为98，除了管理员外一般情况列表不显示
  status: 
    users: [["资料未填写",0], ["正常",1], ["冻结",2], ["未审核",3],["已删除",98]]
    articles: [["暂存",0], ["已发布",1], ["审核不通过",2], ["已删除",98]]
    suggestions: [["未读",0],["已处理",1],["已读",3],["已删除",98]]
  category:
    notification: [["待办任务",1], ["系统消息",2], ["好友短信",3]]
  # 标签
  tags:
    articles: ['党建','人才','档案','办公']
  icons:
    "录入": "fa-pencil-square-o"
    "填写": "fa-pencil"
    "修改": "fa-wrench"
    "审核": "fa-gavel"
    "授权": "fa-unlock"
    "确认": "fa-check-square-o"
    "退回": "fa-times"
    "评价": "fa-thumbs-o-up"
    "删除": "fa-trash-o"
    "移动": "fa-arrows-v"
    "邮件": "fa-envelope"
    "提交": "fa-paper-plane-o"
    "下单": "fa-shopping-cart"
    "打印": "fa-print"
    "标记": "fa-flag"
    "其他": "fa-tag"

development:
  <<: *defaults
  env_tye: '开发模式'
  
test:
  <<: *defaults

production:
  <<: *defaults
  env_tye: '生产模式'
